models/Reservation.php
<?php

namespace app\models;

use app\components\EndTimeValidator;
use app\components\ReservationFailedException;
use app\components\TimeRatioValidator;
use dektrium\user\models\User;
use Yii;
use yii\bootstrap\Html;
use yii\db\ActiveQuery;
use yii\db\Exception;
use yii\db\Expression;

/**
 * This is the model class for table "{{%reservation}}".
 *
 * @property int $id
 * @property int $room_id
 * @property int $user_id
 * @property string $meeting_date
 * @property string $start_time
 * @property string $end_time
 * @property int $status
 *
 * @property Room $room
 * @property User $user
 */
class Reservation extends \yii\db\ActiveRecord
{
    const STATUS_INACTIVE = 0;
    const STATUS_ACTIVE = 1;
    const STATUS_CANCELED_BY_ADMIN = 2;
    const RESERVATION_TIME_RESTRICTION = 30;
    const TIME_RATIO = 15;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%reservation}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['room_id', 'user_id'], 'required'],
            [['room_id', 'user_id', 'status'], 'integer'],
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_INACTIVE, self::STATUS_CANCELED_BY_ADMIN]],
            [['meeting_date'], 'date', 'format' => 'php:Y-m-d'],
            [['start_time', 'end_time'], 'time', 'format' => 'php:H:i'],
            [['start_time', 'end_time'], TimeRatioValidator::className(), 'ratio' => self::TIME_RATIO],
            ['end_time', EndTimeValidator::className(), 'startAttribute' => 'start_time', 'interval' => self::RESERVATION_TIME_RESTRICTION],
            [['room_id'], 'exist', 'skipOnError' => true, 'targetClass' => Room::className(), 'targetAttribute' => ['room_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'room_id' => Yii::t('app', 'Room'),
            'user_id' => Yii::t('app', 'User'),
            'meeting_date' => Yii::t('app', 'Meeting Date'),
            'start_time' => Yii::t('app', 'Start Time'),
            'end_time' => Yii::t('app', 'End Time'),
            'status' => Yii::t('app', 'Reservation status'),
            'room' => Yii::t('app', 'Room'),
            'user' => Yii::t('app', 'User'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRoom()
    {
        return $this->hasOne(Room::className(), ['id' => 'room_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * @return array Status array.
     */
    public static function statusArray()
    {
        return [
            self::STATUS_INACTIVE => Yii::t('app', 'Inactive'),
            self::STATUS_ACTIVE => Yii::t('app', 'Active'),
            self::STATUS_CANCELED_BY_ADMIN => Yii::t('app', 'Canceled by admin'),
        ];
    }

    /**
     * @return array Status array in html.
     */
    public static function statusArrayHtml()
    {
        return [
            self::STATUS_INACTIVE => Html::tag('span', Yii::t('app', 'Inactive'), ['class' => 'label label-default']),
            self::STATUS_ACTIVE => Html::tag('span', Yii::t('app', 'Active'), ['class' => 'label label-success']),
            self::STATUS_CANCELED_BY_ADMIN => Html::tag('span', Yii::t('app', 'Canceled by admin'), ['class' => 'label label-danger']),
        ];
    }

    /**
     * @param $condition
     * @return ActiveQuery
     */
    public function getExistenceCheckingQuery($condition)
    {
        return self::find()->select([new Expression('1')])->where($condition)
            ->andWhere(['status' => Reservation::STATUS_ACTIVE])
            ->andWhere(['meeting_date' => Yii::$app->formatter->asDate($this->meeting_date, 'yyyy-MM-dd')])
            ->andWhere(['or',
                ['and', ['<=', 'start_time', $this->start_time], ['>', 'end_time', $this->start_time]],
                ['and', ['<', 'start_time', $this->end_time], ['>=', 'end_time', $this->end_time]]
            ]);
    }

    /**
     * @return bool
     * @throws ReservationFailedException
     */
    public function makeReservation()
    {
        $transaction = Yii::$app->db->beginTransaction();
        $sql = 'SELECT * FROM ' . Room::tableName() . ' WHERE id = :id FOR UPDATE';
        try {
            //Prevent racing state
            $room = Room::findBySql($sql, [':id' => $this->room_id])->one();

            $existedReservations = $this->getExistenceCheckingQuery(['room_id' => $this->room_id]);

            if (!$existedReservations->exists()) {
                if ($this->save()) {
                    $transaction->commit();
                    return true;
                } else {
                    $message = Yii::t('app', 'An error occurred during saving your reservation');
                }
            } else {
                $message = Yii::t('app', 'This room already reserved by another person');
            }
            $transaction->rollBack();
            throw new ReservationFailedException($message);
        } catch (Exception $exception) {
            $transaction->rollBack();
            throw new ReservationFailedException(Yii::t('app', 'An error occurred during saving your reservation'));
        }
    }
}

controllers/ReservationController.php
<?php

namespace app\controllers;

use Yii;
use app\models\search\RoomSearch;
use app\models\Reservation;
use app\models\search\ReservationSearch;
use app\components\ReservationFailedException;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * ReservationController implements the CRUD actions for Reservation model.
 */
class ReservationController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index'],
                        'roles' => ['reservationIndex']
                    ],
                    [
                        'allow' => true,
                        'actions' => ['deactivate'],
                        'roles' => ['reservationDeactivate'],
                        'roleParams' => function() {
                            return ['reservation' => Reservation::findOne(Yii::$app->request->get('id'))];
                        },
                    ],
                    [
                        'allow' => true,
                        'actions' => ['view'],
                        'roles' => ['reservationView'],
                        'roleParams' => function() {
                            return ['reservation' => Reservation::findOne(Yii::$app->request->get('id'))];
                        },
                    ],
                    [
                        'allow' => true,
                        'actions' => ['my-reservations'],
                        'roles' => ['reservationMyReservations']
                    ],
                    [
                        'allow' => true,
                        'actions' => ['find-room'],
                        'roles' => ['reservationFindRoom']
                    ],
                    [
                        'allow' => true,
                        'actions' => ['reserve'],
                        'roles' => ['reservationReserve']
                    ],
                    [
                        'allow' => true,
                        'actions' => ['delete'],
                        'roles' => ['reservationDelete']
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                    'reserve' => ['POST'],
                    'deactivate' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Reservation models.
     * @return mixed
     */
    public function actionIndex()
    {
        $this->view->title = Yii::t('app', 'All reservations');
        $searchModel = new ReservationSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @param integer $id
     * @return mixed
     */
    public function actionDeactivate($id)
    {
        $reservation = $this->findModel($id);
        $status = ($reservation->user_id == Yii::$app->user->id) ? $reservation::STATUS_INACTIVE : $reservation::STATUS_CANCELED_BY_ADMIN;
        $reservation->updateAttributes(['status' => $status]);

        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * @return string
     */
    public function actionMyReservations()
    {
        $this->view->title = Yii::t('app', 'My reservations');

        $userId = Yii::$app->user->id;
        $searchModel = new ReservationSearch(['user_id' => $userId]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @param $id
     * @return string
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        if (Yii::$app->request->isAjax) {
            return $this->renderAjax('view', [
                'model' => $model,
            ]);
        }

        return $this->render('view', [
                'model' => $model,
        ]);
    }

    /**
     * @return string
     */
    public function actionFindRoom()
    {
        $searchModel = new RoomSearch();
        $dataProvider = $searchModel->findRoom(Yii::$app->request->queryParams);

        return $this->render('find-room', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @param $id
     * @return string
     */
    public function actionReserve($id)
    {
        $searchModel = new RoomSearch();
        $searchModel->load(Yii::$app->request->bodyParams);

        if (!$searchModel->validate()) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($searchModel);
        }

        $reservation = new Reservation([
            'room_id' => $id,
            'user_id' => Yii::$app->user->id,
            'meeting_date' => Yii::$app->formatter->asDate($searchModel->meetingDate, 'yyyy-MM-dd'),
            'start_time' => $searchModel->startTime,
            'end_time' => $searchModel->endTime,
        ]);

        try {
            $reservation->makeReservation();
            Yii::$app->session->setFlash('success', Yii::t('app', 'Selected room is successfully reserved'));
            return $this->redirect(['/reservation/my-reservations']);
        } catch (ReservationFailedException $exception) {
            Yii::$app->session->setFlash('error', $exception->getMessage());
        }

        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * Deletes an existing Reservation model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Reservation model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Reservation the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Reservation::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/reservation/_room.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Room */

?>
<div class="col-lg-4 col-md-6">
    <h2 class="text-center"><?= Html::encode($model->name) ?></h2>
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'capacity',
            [
                'attribute' => 'featureIds',
                'format' => 'raw',
                'value' => $model->featuresAsHtml(),
            ],
        ],
    ]) ?>

    <div class="text-center">
        <?= Html::a(Yii::t('app', 'Reserve'), ['/reservation/reserve', 'id' => $model->id], [
            'class' => 'btn btn-success room-reserve',
            'data' => [
                'source' => '#room-search-form',
            ],
        ]) ?>
    </div>
</div>

views/reservation/_search.php
<?php

use app\models\RoomFeature;
use kartik\date\DatePicker;
use kartik\time\TimePicker;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\RoomSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="reservation-search">

    <?php $form = ActiveForm::begin([
        'id' => 'room-search-form',
        'action' => ['find-room'],
        'method' => 'get',
    ]); ?>

    <div class="ibox float-e-margins">
        <div class="ibox-content">
            <h3><?= Yii::t('app', 'Select room features') ?></h3>

            <div class="row">
                <div class="col-sm-6">
                    <?= $form->field($model, 'name') ?>
                </div>
                <div class="col-sm-6">
                    <?= $form->field($model, 'capacity') ?>
                </div>
            </div>

            <?= $form->field($model, 'featureIds')->checkboxList(RoomFeature::getCheckboxList(), [
                'item' => function ($index, $label, $name, $checked, $value) {
                    $checkedAttribute = ($checked) ? 'checked' : '';
                    return "<input id='feature-{$index}' class='switcher' type='checkbox' {$checkedAttribute}  name='{$name}' value='{$value}'>"
                        . "<label for='feature-{$index}'>{$label}</label>";
                },
            ]) ?>

            <div class="row">
                <div class="col-sm-6">
                    <?= $form->field($model, 'availableOnly', [
                        'template' => '{input}{label}{error}{hint}',
                    ])->checkbox(['class' => 'switcher'], false) ?>
                </div>
            </div>
        </div>
    </div>

    <div class="ibox float-e-margins">
        <div class="ibox-content">
            <h3><?= Yii::t('app', 'Enter the meeting time') ?></h3>

            <div class="row">
                <?php $timePickerOptions = [
                    'pluginOptions' => [
                        'minuteStep' => 15,
                        'showMeridian' => false,
                    ],
                ]; ?>
                <div class="col-sm-4">
                    <?= $form->field($model, 'meetingDate')->widget(DatePicker::classname(), [
                        'options' => ['placeholder' => Yii::t('app', 'Select meeting date')],
                        'removeButton' => false,
                        'pluginOptions' => [
                            'autoclose' => true,
                            'format' => 'dd.mm.yyyy'
                        ]
                    ]); ?>
                </div>
                <div class="col-sm-4">
                    <?= $form->field($model, 'startTime')->widget(TimePicker::classname(), $timePickerOptions); ?>
                </div>
                <div class="col-sm-4">
                    <?= $form->field($model, 'endTime')->widget(TimePicker::classname(), $timePickerOptions); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/reservation/find-room.php
<?php

use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\ReservationSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Find room');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="reservation-index">
    <?= $this->render('_search', ['model' => $searchModel]); ?>

    <?= ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => '_room',
        'layout' => '{summary} <div class="row">{items}</div> {pager}',
    ]); ?>
</div>

views/reservation/index.php
<?php

use app\models\Reservation;
use kartik\date\DatePicker;
use kartik\time\TimePicker;
use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\ReservationSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->params['breadcrumbs'][] = $this->title;
?>
<div class="reservation-index">

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
                'attribute' => 'id',
                'options' => ['style' => 'width: 50px']
            ],
            [
                'attribute' => 'room',
                'value' => 'room.name',
            ],
            [
                'attribute' => 'user',
                'value' => 'user.username',
                'visible' => Yii::$app->user->can('administrator'),
            ],
            [
                'attribute' => 'meeting_date',
                'filter' => DatePicker::widget([
                    'model' => $searchModel,
                    'type' => DatePicker::TYPE_RANGE,
                    'attribute' => 'meetingDateFrom',
                    'attribute2' => 'meetingDateTo',
                    'separator' => '',
                    'pluginOptions' => [
                        'autoclose' => true,
                        'format' => 'yyyy-mm-dd',
                    ],
                ]),
            ],
            [
                'attribute' => 'start_time',
                'filter' => \yii\widgets\MaskedInput::widget([
                    'model' => $searchModel,
                    'attribute' => 'start_time',
                    'mask' => '99:99',
                ]),
            ],
            [
                'attribute' => 'end_time',
                'filter' => \yii\widgets\MaskedInput::widget([
                    'model' => $searchModel,
                    'attribute' => 'end_time',
                    'mask' => '99:99',
                ]),
            ],
            [
                'attribute' => 'status',
                'filter' => Reservation::statusArray(),
                'content' => function ($data) {
                    return Reservation::statusArrayHtml()[$data->status];
                },
            ],

            [
                'class' => 'yii\grid\ActionColumn',
                'options' => ['style' => 'width: 60px;'],
                'template' => '{view} {deactivate}',
                'buttons' => [
                    'view' => function ($url, $model, $key) {
                        $icon = Html::tag('span', '', ['class' => "glyphicon glyphicon-eye-open"]);
                        return Html::a($icon, ['/reservation/view', 'id' => $key],
                            [
                                'title' => Yii::t('yii', 'View'),
                                'data' => [
                                    'toggle' => 'modal',
                                    'target' => '#reservation-view-modal',
                                    'pjax' => 0,
                                ],
                            ]);
                    },
                    'deactivate' => function ($url, $model, $key) {
                        $icon = Html::tag('span', '', ['class' => "glyphicon glyphicon-remove"]);
                        return Html::a($icon, ['/reservation/deactivate', 'id' => $key],
                            [
                                'title' => Yii::t('app', 'Cancel'),
                                'data' => [
                                    'method' => 'post',
                                    'confirm' => Yii::t('app', 'Are you sure you want to deactivate this reservation?')
                                ],
                            ]);
                    }
                ],
                'visibleButtons' => [
                    'view' => function ($model, $key, $index) {
                             return Yii::$app->user->can('reservationView', ['reservation' => $model]);
                         },
                    'deactivate' => function ($model, $key, $index) {
                        return $model->status == Reservation::STATUS_ACTIVE;
                    },
                ],
            ],
        ],
    ]); ?>
</div>

<?= Modal::widget([
    'id' => 'reservation-view-modal',
    'header' => Yii::t('app', 'View reservation'),
    'options' => ['class' => 'ajax-modal'],
    'toggleButton' => false,
]); ?>

views/reservation/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Reservation */

$this->title = Yii::t('app', 'Meeting Date') . ': ' . $model->meeting_date;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'View reservation'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="room-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            [
                'attribute' => 'user.username',
                'visible' => Yii::$app->user->can('administrator'),
            ],
            'start_time',
            'end_time',
            'room.name',
            'room.capacity',
            [
                'attribute' => 'room.featureIds',
                'format' => 'raw',
                'value' => $model->room->featuresAsHtml(),
            ],
        ],
    ]) ?>

</div>