controllers/ReservationController.php
<?php

namespace app\controllers;

use Yii;
use app\models\search\RoomSearch;
use app\models\Reservation;
use app\models\search\ReservationSearch;
use app\components\ReservationFailedException;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * ReservationController implements the CRUD actions for Reservation model.
 */
class ReservationController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index'],
                        'roles' => ['reservationIndex']
                    ],
                    [
                        'allow' => true,
                        'actions' => ['deactivate'],
                        'roles' => ['reservationDeactivate'],
                        'roleParams' => function() {
                            return ['reservation' => Reservation::findOne(Yii::$app->request->get('id'))];
                        },
                    ],
                    [
                        'allow' => true,
                        'actions' => ['view'],
                        'roles' => ['reservationView'],
                        'roleParams' => function() {
                            return ['reservation' => Reservation::findOne(Yii::$app->request->get('id'))];
                        },
                    ],
                    [
                        'allow' => true,
                        'actions' => ['my-reservations'],
                        'roles' => ['reservationMyReservations']
                    ],
                    [
                        'allow' => true,
                        'actions' => ['find-room'],
                        'roles' => ['reservationFindRoom']
                    ],
                    [
                        'allow' => true,
                        'actions' => ['reserve'],
                        'roles' => ['reservationReserve']
                    ],
                    [
                        'allow' => true,
                        'actions' => ['delete'],
                        'roles' => ['reservationDelete']
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                    'reserve' => ['POST'],
                    'deactivate' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Reservation models.
     * @return mixed
     */
    public function actionIndex()
    {
        $this->view->title = Yii::t('app', 'All reservations');
        $searchModel = new ReservationSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @param integer $id
     * @return mixed
     */
    public function actionDeactivate($id)
    {
        $reservation = $this->findModel($id);
        $status = ($reservation->user_id == Yii::$app->user->id) ? $reservation::STATUS_INACTIVE : $reservation::STATUS_CANCELED_BY_ADMIN;
        $reservation->updateAttributes(['status' => $status]);

        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * @return string
     */
    public function actionMyReservations()
    {
        $this->view->title = Yii::t('app', 'My reservations');

        $userId = Yii::$app->user->id;
        $searchModel = new ReservationSearch(['user_id' => $userId]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @param $id
     * @return string
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        if (Yii::$app->request->isAjax) {
            return $this->renderAjax('view', [
                'model' => $model,
            ]);
        }

        return $this->render('view', [
                'model' => $model,
        ]);
    }

    /**
     * @return string
     */
    public function actionFindRoom()
    {
        $searchModel = new RoomSearch();
        $dataProvider = $searchModel->findRoom(Yii::$app->request->queryParams);

        return $this->render('find-room', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @param $id
     * @return string
     */
    public function actionReserve($id)
    {
        $searchModel = new RoomSearch();
        $searchModel->load(Yii::$app->request->bodyParams);

        if (!$searchModel->validate()) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($searchModel);
        }

        $reservation = new Reservation([
            'room_id' => $id,
            'user_id' => Yii::$app->user->id,
            'meeting_date' => Yii::$app->formatter->asDate($searchModel->meetingDate, 'yyyy-MM-dd'),
            'start_time' => $searchModel->startTime,
            'end_time' => $searchModel->endTime,
        ]);

        try {
            $reservation->makeReservation();
            Yii::$app->session->setFlash('success', Yii::t('app', 'Selected room is successfully reserved'));
            return $this->redirect(['/reservation/my-reservations']);
        } catch (ReservationFailedException $exception) {
            Yii::$app->session->setFlash('error', $exception->getMessage());
        }

        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * Deletes an existing Reservation model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Reservation model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Reservation the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Reservation::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/RoomController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Room;
use app\models\search\RoomSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * RoomController implements the CRUD actions for Room model.
 */
class RoomController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index'],
                        'roles' => ['roomIndex']
                    ],
                    [
                        'allow' => true,
                        'actions' => ['create'],
                        'roles' => ['roomCreate']
                    ],
                    [
                        'allow' => true,
                        'actions' => ['update'],
                        'roles' => ['roomUpdate']
                    ],
                    [
                        'allow' => true,
                        'actions' => ['delete'],
                        'roles' => ['roomDelete']
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Room models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new RoomSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Room model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Room model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Room();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Room model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Room model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Room model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Room the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Room::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/layouts/_header.php
<?php
use yii\helpers\Url;

?>

<nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary" href="#"><i class="fa fa-bars"></i></a>
    </div>
    <ul class="nav navbar-top-links navbar-right">
        <li>
            <a href="<?= Url::toRoute(['/user/security/logout']) ?>" data-method="post">
                <i class="fa fa-sign-out"></i> Выйти
            </a>
        </li>
    </ul>
</nav>

views/layouts/_heading.php
<?php
use yii\widgets\Breadcrumbs;

/* @var $this \yii\web\View */
?>

<h2><?= $this->title ?></h2>

<?= Breadcrumbs::widget([
    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
    'activeItemTemplate' => "<li class=\"active\"><strong>{link}</strong></li>\n"
]) ?>

views/layouts/_sidebar.php
<?php
use app\widgets\Menu;

?>

<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <?php
        $header = [
            'name' => Yii::$app->user->identity->username,
            'email' => Yii::$app->user->identity->email,
            'url' => ['/user/profile/index'],
        ];

        $menu = [
            [
                'label' => Yii::t('app', 'Home'),
                'url' => ['/site/index'],
                'icon' => 'fa fa-home',
            ],
            [
                'label' => Yii::t('app', 'Profile'),
                'url' => ['#'],
                'icon' => 'fa fa-user',
                'active' => $this->context->id === 'settings',
                'items' => [
                    [
                        'label' => Yii::t('user', 'Account settings'),
                        'url' => ['/user/settings/account'],
                    ],
                    [
                        'label' => Yii::t('user', 'Profile settings'),
                        'url' => ['/user/settings/profile'],
                    ],
                    [
                        'label' => Yii::t('user', 'Networks'),
                        'url' => ['/user/settings/networks'],
                    ],
                ],
            ],
            [
                'label' => Yii::t('app', 'Rooms'),
                'url' => ['/room/index'],
                'icon' => 'fa fa-pie-chart',
                'active' => $this->context->id === 'room',
                'visible' => Yii::$app->user->can('roomManage'),
            ],
            [
                'label' => Yii::t('app', 'Reservations'),
                'url' => ['#'],
                'icon' => 'fa fa-star',
                'active' => $this->context->id === 'reservation',
                'items' => [
                    [
                        'label' => Yii::t('app', 'All reservations'),
                        'url' => ['/reservation/index'],
                        'visible' => Yii::$app->user->can('reservationIndex'),
                    ],
                    [
                        'label' => Yii::t('app', 'My reservations'),
                        'url' => ['/reservation/my-reservations'],
                        'visible' => Yii::$app->user->can('reservationMyReservations'),
                    ],
                    [
                        'label' => Yii::t('app', 'Find room'),
                        'url' => ['/reservation/find-room'],
                        'visible' => Yii::$app->user->can('reservationFindRoom'),
                    ],
                ],
                'visible' => Yii::$app->user->can('user'),
            ],
            [
                'label' => Yii::t('app', 'Users'),
                'url' => ['/user/admin/index'],
                'icon' => 'fa fa-users',
                'visible' => Yii::$app->user->can('administrator'),
            ],
        ];
        ?>

        <?= Menu::widget([
            'options' => ['class' => 'nav metismenu', 'id' => 'side-menu'],
            'submenuTemplate' => "\n<ul class='nav nav-second-level collapse' {show}>\n{items}\n</ul>\n",
            'items' => $menu,
            'header' => $header,
        ]) ?>

    </div>
</nav>

views/layouts/empty.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\assets\AppHeaderAsset;
use app\widgets\Alert;
use yii\helpers\Html;

AppHeaderAsset::register($this);
?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">

<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>

<body class="gray-bg">
<?php $this->beginBody() ?>
<?= Alert::widget() ?>
<?= $content ?>
<?php $this->endBody() ?>
</body>

</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\assets\AppFooterAsset;
use app\assets\AppHeaderAsset;
use yii\helpers\Html;
use app\widgets\Alert;


AppHeaderAsset::register($this);
AppFooterAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>

<body>
<?php $this->beginBody() ?>

<div id="wrapper">

    <?= $this->render('_sidebar') ?>

    <div id="page-wrapper" class="gray-bg">

        <section class="row border-bottom">
            <?= $this->render('_header') ?>
        </section>

        <section class="row border-bottom white-bg page-heading">
            <div class="col-sm-12">
                <?= $this->render('_heading') ?>
            </div>
        </section>

        <main class="wrapper wrapper-content">
            <?= Alert::widget() ?>
            <section><?= $content ?></section>
        </main>

    </div>

</div>
<?php $this->endBody() ?>
</body>

</html>
<?php $this->endPage() ?>